# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hKLNyTwg37kQqIKLooz0tzbhuhd_-dtP
"""

import pandas as pd
import numpy as np
import seaborn as sns

df = pd.read_csv("/content/Iris.csv")

df.head()

df.tail()

df.info()

df.describe()

df.mean()

df.median()

df.isnull().sum()

df.shape

df.size

df.columns

df.drop("Id",axis=1,inplace=True)
df.head()

sns.pairplot(df.iloc[:,:],hue='Species')

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics

X=df.iloc[:,0:4]
Y=df["Species"]
X.head()

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

print("Train Shape",X_train.shape)
print("Test Shape",X_test.shape)

log = LogisticRegression()
log.fit(X_train,Y_train)
prediction=log.predict(X_test)
print('The accuracy of the Logistic Regression is',metrics.accuracy_score(prediction,Y_test))

from sklearn.neighbors import KNeighborsClassifier

knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,Y_train)
prediction=knn.predict(X_test)
print('The accuracy of the KNN is',metrics.accuracy_score(prediction,Y_test))

from sklearn.tree import DecisionTreeClassifier

tree=DecisionTreeClassifier()
tree.fit(X_train,Y_train)
prediction=tree.predict(X_test)
print('The accuracy of the Decision Tree is',metrics.accuracy_score(prediction,Y_test))

